_target_: navsim.agents.vdiffusiondrivev2_minmaxnorm.transfuser_agent.TransfuserAgent
_convert_: 'all'

config:
  _target_: navsim.agents.vdiffusiondrivev2_minmaxnorm.transfuser_config.TransfuserConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False

checkpoint_path: null
lr: 6e-4